name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  issue_opened_or_reopened:
    name: issue_opened_or_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move issue to Awaiting Triage
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.KPACK_BOT_PAT }}
          organization: pivotal
          project_id: 18
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: "Awaiting Triage"
